server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/project_Y?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li4CgQ8WOFU3RyjK
            client-secret: 59aa60b6ed40b30306e89c8b59cbfa7ddd622922
            scope: user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

mybatis:
  type-aliases-package: org.example.vo
  mapper-locations: classpath:/mappers/**/*.xml

logging:
  level:
    org.mybatis: DEBUG
    org.example.repository: DEBUG


